from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from bbi_os.client_execution.models import ClientExecutionRecord
from bbi_os.client_monetization.models import ClientPlan, UsageEvent

TaskRecord = Dict[str, Any]


@runtime_checkable
class TaskRepository(Protocol):
    def list(self) -> List[TaskRecord]: ...

    def get(self, task_id: str) -> Optional[TaskRecord]: ...

    def exists(self, task_id: str) -> bool: ...

    def count(self) -> int: ...

    def save(self, task: TaskRecord) -> TaskRecord: ...

    def delete(self, task_id: str) -> bool: ...


@runtime_checkable
class ExecutionStateRepositoryContract(Protocol):
    def save(self, record: ClientExecutionRecord) -> ClientExecutionRecord: ...

    def get(self, execution_id: str) -> Optional[ClientExecutionRecord]: ...

    def exists(self, execution_id: str) -> bool: ...

    def count(self) -> int: ...

    def list(self) -> List[ClientExecutionRecord]: ...

    def latest_for_client(self, client_id: str) -> Optional[ClientExecutionRecord]: ...

    def list_for_client(self, client_id: str) -> List[ClientExecutionRecord]: ...


@runtime_checkable
class ClientPlanRepository(Protocol):
    def plan_for(self, client_id: str) -> ClientPlan: ...

    def assign(self, client_id: str, plan_id: str) -> ClientPlan: ...


@runtime_checkable
class UsageRepository(Protocol):
    def record(self, event: UsageEvent) -> UsageEvent: ...

    def for_client(self, client_id: str) -> List[UsageEvent]: ...

    def total_units(self, client_id: str) -> int: ...

    def recent_count(self, client_id: str, minutes: int = 1) -> int: ...
